# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d2796c7a8ce76b093f05427192ab1f8"
name = "tingee-payment-app"
application_url = "https://tingee-payment-app.onrender.com"
embedded = true

[access_scopes]
scopes = "read_orders,write_orders"

[webhooks]
api_version = "2025-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://tingee-payment-app.onrender.com/webhooks/customers/redact"
  customer_data_request_url = "https://tingee-payment-app.onrender.com/webhooks/customers/data_request"
  shop_deletion_url = "https://tingee-payment-app.onrender.com/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]


[auth]
redirect_urls = [ "https://tingee-payment-app.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true

[[extensions]]
type = "ui_extension"
handle = "order-status-ui"
path = "extensions/order-status-ui"
